# Uncomment the next line to define a global platform for your project
# platform :ios, '17.0'

target 'AdminApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.7.0'
  pod 'Then'
  pod 'Alamofire'
  pod 'Kingfisher', '~> 7.0'

  # Pods for AdminApp

  target 'AdminAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AdminAppUITests' do
    # Pods for testing
  end

end
